// RBotFirmware
// Rob Dobson 2016-2018

#include "RobotConfigurations.h"

const char *RobotConfigurations::_robotConfigs[] = {

"{"
" \"robotType\": \"SandTableScara\","
" \"cmdsAtStart\": \"\","
" \"webui\":\"sand\","
" \"evaluators\":"
" {"
"   \"thrContinue\": 0"
" }"
" ,"
" \"robotGeom\":"
" {"
"   \"model\": \"SingleArmScara\","
"   \"homing\":"
"   {"
"     \"homingSeq\":\"FR7;A+10000n;B-10000;#;A+1000N;B-1000;#;B+10000n;#;B+1000N;#;A=h;B=h;$\","
"     \"maxHomingSecs\": 90"
"   }"
"   ,"
"   \"blockDistanceMM\": 1,"
"   \"allowOutOfBounds\": 0,"
"   \"stepEnablePin\": \"12\","
"   \"stepEnLev\": 0,"
"   \"stepDisableSecs\": 10,"
"   \"axis0\":"
"   {"
"     \"maxSpeed\": 10,"
"     \"maxAcc\": 20,"
"     \"maxRPM\": 2,"
"     \"stepsPerRot\": 9600,"
"     \"unitsPerRot\": 628.318,"
"     \"maxVal\": 150,"
"     \"stepPin\": \"14\","
"     \"dirnPin\": \"32\","
"     \"endStop0\":"
"     {"
"       \"sensePin\": \"36\","
"       \"actLvl\": 1"
"     }"
"   }"
"   ,"
"   \"axis1\":"
"   {"
"     \"maxSpeed\": 10,"
"     \"maxAcc\": 20,"
"     \"maxRPM\": 2,"
"     \"stepsPerRot\": 9600,"
"     \"unitsPerRot\": 628.318,"
"     \"maxVal\": 150,"
"     \"stepPin\": \"27\","
"     \"dirnPin\": \"15\","
"     \"endStop0\":"
"     {"
"       \"sensePin\": \"39\","
"       \"actLvl\": 1"
"     }"
"   }"
" }"
" ,"
" \"fileManager\":"
" {"
"   \"spiffsEnabled\": 1,"
"   \"spiffsFormatIfCorrupt\": 1,"
"   \"sdEnabled\": 1,"
"   \"sdMOSI\": \"MOSI\","
"   \"sdMISO\": \"MISO\","
"   \"sdCLK\": \"SCK\","
"   \"sdCS\": \"SS\""
" }"
" ,"
" \"wifiLed\":"
" {"
"   \"hwPin\": \"13\","
"   \"onLevel\": 1,"
"   \"onMs\": 200,"
"   \"shortOffMs\": 200,"
"   \"longOffMs\": 750"
" }"
" ,"
" \"ledStrip\":"
" {"
"   \"ledPin\": \"4\","
"   \"ledOn\":0,"
"   \"ledValue\":0,"
"   \"autoDim\":0"
" }"
"}"
,

// XYBot
"{"
" \"robotType\": \"XYBot\","
" \"cmdsAtStart\": \"\","
" \"webui\":\"cnc\","
" \"robotGeom\":"
" {"
"   \"model\": \"Cartesian\","
"   \"blockDistanceMM\": 1,"
"   \"allowOutOfBounds\": 0,"
"   \"stepEnablePin\": \"21\","
"   \"stepEnLev\": 0,"
"   \"stepDisableSecs\": 10,"
"   \"axis0\":"
"   {"
"     \"maxSpeed\": 50,"
"     \"maxAcc\": 50,"
"     \"stepsPerRot\": 3200,"
"     \"unitsPerRot\": 16,"
"     \"maxRPM\": 200,"
"     \"maxVal\": 200,"
"     \"stepPin\": \"27\","
"     \"dirnPin\": \"33\","
"     \"endStop0\":"
"     {"
"       \"sensePin\": \"39\","
"       \"actLvl\": 0,"
"       \"inputType\": \"INPUT_PULLUP\""
"     }"
"   }"
"   ,"
"   \"axis1\":"
"   {"
"     \"maxSpeed\": 50,"
"     \"maxAcc\": 50,"
"     \"stepsPerRot\": 3200,"
"     \"unitsPerRot\": 16,"
"     \"maxRPM\": 200,"
"     \"maxVal\": 200,"
"     \"stepPin\": \"12\","
"     \"dirnPin\": \"16\","
"     \"endStop0\":"
"     {"
"       \"sensePin\": \"36\","
"       \"actLvl\": 0,"
"       \"inputType\": \"INPUT_PULLUP\""
"     }"
"   }"
" }"
" ,"
" \"fileManager\":"
" {"
"   \"spiffsEnabled\": 1,"
"   \"spiffsFormatIfCorrupt\": 1,"
"   \"sdEnabled\": 1,"
"   \"sdMOSI\": \"23\","
"   \"sdMISO\": \"19\","
"   \"sdCLK\": \"18\","
"   \"sdCS\": \"4\""
" }"
" ,"
" \"wifiLed\":"
" {"
"   \"hwPin\": \"14\","
"   \"onLevel\": 1,"
"   \"onMs\": 200,"
"   \"shortOffMs\": 200,"
"   \"longOffMs\": 750"
" }"
"}"

};

const int RobotConfigurations::_numRobotConfigurations = sizeof(RobotConfigurations::_robotConfigs) / sizeof(const char *);
